//! Byte-for-byte parity tests against project files generated by the original
//! Python implementation (recorded under tests/fixtures/golden/). The scraper
//! `parse` functions run over recorded fixtures, so no network is needed.

use xrc::renderer::render_rust_template;
use xrc::scrapers::{ProblemData, dmoj, leetcode};

fn assert_matches_golden(files: &[(String, String)], project: &str) {
    for (rel_path, content) in files {
        let golden_path = format!("tests/fixtures/golden/{project}/{rel_path}");
        let expected = std::fs::read_to_string(&golden_path)
            .unwrap_or_else(|e| panic!("missing golden file {golden_path}: {e}"));
        // the writer trims and appends a single trailing newline
        let written = format!("{}\n", content.trim());
        assert_eq!(
            written, expected,
            "generated {rel_path} differs from Python output ({golden_path})"
        );
    }
}

#[test]
fn dmoj_a_plus_b_matches_python_output() {
    let html = include_str!("fixtures/dmoj_aplusb.html");
    let data = dmoj::parse(html).unwrap();
    assert_eq!(data.title, "A Plus B");
    let files = render_rust_template(&data, "dmoj").unwrap();
    assert_eq!(files.len(), 3);
    assert_matches_golden(&files, "a_plus_b");
}

fn leetcode_data(fixture: &str, slug: &str) -> ProblemData {
    let response: serde_json::Value = serde_json::from_str(fixture).unwrap();
    leetcode::parse_question(&response["data"]["question"], slug).unwrap()
}

#[test]
fn leetcode_two_sum_matches_python_output() {
    let data = leetcode_data(include_str!("fixtures/leetcode_two_sum.json"), "two-sum");
    assert_eq!(data.title, "Two Sum");
    let files = render_rust_template(&data, "leetcode").unwrap();
    assert_eq!(files.len(), 2);
    assert_matches_golden(&files, "two_sum");
}

#[test]
fn leetcode_valid_palindrome_matches_python_output() {
    let data = leetcode_data(
        include_str!("fixtures/leetcode_valid_palindrome.json"),
        "valid-palindrome",
    );
    assert_eq!(data.title, "Valid Palindrome");
    let files = render_rust_template(&data, "leetcode").unwrap();
    assert_matches_golden(&files, "valid_palindrome");
}
